gitignore

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -27,6 +27,11 @@ jobs:
         run: |
           forge --version
 
+      - name: Run Forge fmt
+        run: |
+          forge fmt --check || echo "⚠️ Formatting differences detected, skipping fail"
+        id: fmt
+
       #      - name: Run Forge fmt
       #        run: |
       #          forge fmt --check
